-- 0007_dispatches.sql — per-user dispatch history + FTS5 index.
--
-- Why: F205 epic E003 (web dashboard) needs server-side history of every
-- dispatched job so the History screen can render after a browser refresh,
-- and so the SPA can resume an SSE stream after a tab reload (via the
-- DispatchStream Durable Object).
--
-- The worker is a CONTROL PLANE: the SPA proxies the actual LLM streams
-- to/from the user's local `spectyn serve` daemon directly (CORS-allowed
-- origin in F206). What lives here is METADATA: the job record, status
-- transitions, and the final transcript chunk-by-chunk for replay. The
-- SPA writes chunks here as they arrive locally; other tabs subscribe to
-- the Durable Object to see them mirrored.
--
-- FTS5: a parallel virtual table indexes `prompt` + truncated `result`
-- (first 4 KB) so the History screen's text search can hit a query plan
-- that uses the FTS index instead of a full table scan.
--
-- Apply: wrangler d1 execute phantommesh-prod --remote --file=./migrations/0007_dispatches.sql

CREATE TABLE IF NOT EXISTS dispatches (
    job_id        TEXT    NOT NULL,                  -- uuid generated by worker on /start
    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    peer          TEXT    NOT NULL,                  -- target peer name
    provider      TEXT    NOT NULL DEFAULT '',       -- LLM provider id (groq / openai / etc.)
    model         TEXT    NOT NULL DEFAULT '',       -- model id within the provider
    prompt        TEXT    NOT NULL DEFAULT '',       -- user-typed prompt
    required_caps TEXT    NOT NULL DEFAULT '[]',     -- JSON array of cap strings
    status        TEXT    NOT NULL DEFAULT 'pending',-- pending | running | done | cancelled | error
    result        TEXT    NOT NULL DEFAULT '',       -- accumulated assistant output (truncated for FTS)
    error_message TEXT,                              -- non-null when status = 'error'
    started_at    INTEGER NOT NULL,                  -- unix ms
    completed_at  INTEGER,                           -- unix ms; null while running
    PRIMARY KEY (user_id, job_id)
);

CREATE INDEX IF NOT EXISTS idx_dispatches_user_started
    ON dispatches(user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_dispatches_user_peer
    ON dispatches(user_id, peer, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_dispatches_user_status
    ON dispatches(user_id, status, started_at DESC);

-- FTS5 virtual table — contentless mode (no shadow row duplication).
-- We feed prompt + the leading 4 KB of result into this index so the
-- History screen's `q=` filter uses FTS instead of LIKE-scan.
-- F205 acceptance criterion: `EXPLAIN QUERY PLAN` shows FTS usage.
CREATE VIRTUAL TABLE IF NOT EXISTS dispatches_fts USING fts5(
    prompt,
    result,
    content=''  -- contentless: rows managed by application triggers below
);

-- Triggers keep the FTS index in sync with the dispatches table. We
-- truncate result to 4096 chars at index time to bound row size — long
-- transcripts still searchable on prompt + their opening.
CREATE TRIGGER IF NOT EXISTS dispatches_ai AFTER INSERT ON dispatches BEGIN
    INSERT INTO dispatches_fts(rowid, prompt, result)
    VALUES (new.rowid, new.prompt, substr(new.result, 1, 4096));
END;

CREATE TRIGGER IF NOT EXISTS dispatches_au AFTER UPDATE ON dispatches BEGIN
    INSERT INTO dispatches_fts(dispatches_fts, rowid, prompt, result)
    VALUES('delete', old.rowid, old.prompt, substr(old.result, 1, 4096));
    INSERT INTO dispatches_fts(rowid, prompt, result)
    VALUES (new.rowid, new.prompt, substr(new.result, 1, 4096));
END;

CREATE TRIGGER IF NOT EXISTS dispatches_ad AFTER DELETE ON dispatches BEGIN
    INSERT INTO dispatches_fts(dispatches_fts, rowid, prompt, result)
    VALUES('delete', old.rowid, old.prompt, substr(old.result, 1, 4096));
END;
