-- 0005_user_sessions.sql — live TUI session presence.
--
-- Why: peers.json + healthz tells you "node is reachable", but not
-- "I have a TUI open on Z13 right now in phantommesh-io". Each TUI
-- pings here on launch + every 30s; rows older than 60s are
-- considered stale by the read endpoint.
--
-- Not encrypted: machine name + cwd + agent name aren't secrets,
-- and the row is scoped to user_id (RLS via Bearer token).
--
-- Apply: wrangler d1 execute phantommesh-prod --remote --file=./migrations/0005_user_sessions.sql

CREATE TABLE IF NOT EXISTS user_active_sessions (
    id           TEXT    NOT NULL,                    -- uuid generated by client at TUI launch
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    machine      TEXT    NOT NULL,                    -- node name, e.g. "ayaneo" / "yoyogood"
    agent        TEXT    NOT NULL DEFAULT 'master',   -- selected agent
    cwd          TEXT    NOT NULL DEFAULT '',         -- working directory
    started_at   INTEGER NOT NULL,                    -- unix seconds
    last_seen_at INTEGER NOT NULL,                    -- unix seconds (updated by heartbeat)
    PRIMARY KEY (user_id, id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_seen
    ON user_active_sessions(user_id, last_seen_at);
