#!/usr/bin/env bash
# app/src-tauri/android/inject.sh
#
# Inject tracked custom Android Kotlin + resources into the (gitignored,
# Tauri-regenerated) gen/android project before building the APK.
#
# WHY: app/src-tauri/gen/android/ is gitignored (full Tauri mobile project,
# regenerated by `tauri android init`). Custom hand-written Kotlin
# (MeshNodeService, FocusQuickTile, ...) + resources live HERE (tracked) and
# get copied in at build time so they survive regeneration + stay in version
# control. (Discovered 2026-05-28: custom code was previously only in the
# gitignored gen/ dir = never tracked, would be lost on regen.)
#
# Usage (run before `tauri android build` / gradle assemble):
#   bash app/src-tauri/android/inject.sh
#
# Idempotent — safe to re-run.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEN="$HERE/../gen/android/app/src/main"
PKG_DIR="$GEN/java/ai/phantommesh/app"

# Resolve a WORKING python for the manifest/gradle patches. On Windows the bare
# `python3` is often the Microsoft Store execution-alias stub (exits ~49, opens
# the Store) — so probe candidates and pick one that actually runs. Override
# with $PHANTOM_PY if needed.
PY=""
for cand in "${PHANTOM_PY:-}" python3 python py; do
    [ -z "$cand" ] && continue
    if "$cand" -c "import sys" >/dev/null 2>&1; then PY="$cand"; break; fi
done
if [ -z "$PY" ]; then
    echo "[inject] ERROR: no working python found (tried python3/python/py)."
    echo "[inject] install Python or set PHANTOM_PY=/path/to/python; needed for manifest patches."
    exit 1
fi
echo "[inject] using python: $PY ($($PY --version 2>&1))"

if [ ! -d "$GEN" ]; then
    echo "[inject] gen/android not found at $GEN"
    echo "[inject] run 'tauri android init' first (or 'npm run tauri android init')"
    exit 1
fi

echo "[inject] copying custom Kotlin → $PKG_DIR"
mkdir -p "$PKG_DIR"
cp -v "$HERE"/kotlin/*.kt "$PKG_DIR/"

echo "[inject] copying drawables"
mkdir -p "$GEN/res/drawable"
cp -v "$HERE"/res/drawable/*.xml "$GEN/res/drawable/" 2>/dev/null || true

echo "[inject] copying res/xml (appwidget providers)"
mkdir -p "$GEN/res/xml"
cp -v "$HERE"/res/xml/*.xml "$GEN/res/xml/" 2>/dev/null || true

echo "[inject] merging custom strings"
# strings-phantom.xml already contains app_name + custom strings; overwrite the
# generated strings.xml (it only has app_name + main_activity_title which we keep).
cp -v "$HERE/res/values/strings-phantom.xml" "$GEN/res/values/strings.xml"

echo "[inject] applying Material 3 theme + phantom color tokens (SPEC-33 §10.1)"
# Override the M2 scaffold theme with the Material 3 phantom theme + tokens. The
# generated AndroidManifest already points <application android:theme> at
# @style/Theme.phantom_mesh_app, so redefining that style here is enough.
cp -v "$HERE/res/values/colors.xml" "$GEN/res/values/colors.xml"
cp -v "$HERE/res/values/themes.xml" "$GEN/res/values/themes.xml"
mkdir -p "$GEN/res/values-night"
cp -v "$HERE/res/values-night/themes.xml" "$GEN/res/values-night/themes.xml"

# Manifest patch: register FocusQuickTile service if not already present.
MANIFEST="$GEN/AndroidManifest.xml"
if [ -f "$MANIFEST" ] && ! grep -q "FocusQuickTile" "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — registering FocusQuickTile"
    # Insert the tile service block after the MeshNodeService closing tag.
    "$PY" - "$MANIFEST" <<'PY'
import sys, re
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
tile = '''
        <!-- SPEC-34 §10E Quick Settings tile (injected by android/inject.sh) -->
        <service
            android:name=".FocusQuickTile"
            android:exported="true"
            android:icon="@drawable/ic_focus_tile"
            android:label="@string/focus_tile_label"
            android:permission="android.permission.BIND_QUICK_SETTINGS_TILE">
            <intent-filter>
                <action android:name="android.service.quicksettings.action.QS_TILE" />
            </intent-filter>
        </service>
'''
# Insert right before the FileProvider <provider ...> block (stable anchor).
anchor = "        <provider"
if "FocusQuickTile" not in s and anchor in s:
    s = s.replace(anchor, tile + "\n" + anchor, 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  manifest patched")
else:
    print("  manifest already has tile or anchor missing")
PY
else
    echo "[inject] manifest already registers FocusQuickTile (skip)"
fi

# Manifest patch: register the persistent MeshNodeService foreground service.
#
# WHY: MeshNodeService.kt is copied in (above) but the Tauri-generated manifest
# only declares MainActivity + the FileProvider — no <service>. On targetSdk 34
# a foreground service MUST be declared with android:foregroundServiceType AND
# the app must hold the matching FOREGROUND_SERVICE_* permission, or
# startForeground() throws (Android 14 enforcement). MeshNodeService calls
# startForeground in onStartCommand, so it needs both.
#
# FGS TYPE CHOICE — specialUse:
#   MeshNodeService's defining job is a persistent always-on mesh HTTP node that
#   survives backgrounding / swipe-away (START_STICKY). That long-lived
#   "keep the node reachable" purpose maps to none of the predefined FGS types
#   (mediaPlayback / location / dataSync / connectedDevice / etc.), so the
#   Android-14 catch-all `specialUse` is the correct declaration. The focus path
#   *may* touch the microphone, but recording is not the service's purpose, and
#   declaring `microphone` would (a) misrepresent the service and (b) impose
#   stricter runtime mic-permission gating on a node whose main job is HTTP.
#   `specialUse` REQUIRES an in-service <property> declaring the subtype, hence
#   PROPERTY_SPECIAL_USE_FGS_SUBTYPE=mesh_node below.
if [ -f "$MANIFEST" ] && ! grep -q 'android:name=".MeshNodeService"' "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — registering MeshNodeService (FGS specialUse)"
    "$PY" - "$MANIFEST" <<'PY'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
service = '''
        <!-- Persistent mesh node + SPEC-21 focus host (injected by android/inject.sh).
             FGS type specialUse: always-on node fits no predefined FGS category. -->
        <service
            android:name=".MeshNodeService"
            android:exported="false"
            android:foregroundServiceType="specialUse">
            <property
                android:name="android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE"
                android:value="mesh_node" />
        </service>
'''
anchor = "        <provider"
if 'android:name=".MeshNodeService"' not in s and anchor in s:
    s = s.replace(anchor, service + "\n" + anchor, 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  manifest patched (MeshNodeService)")
else:
    print("  manifest already has MeshNodeService or anchor missing")
PY
else
    echo "[inject] manifest already registers MeshNodeService (skip)"
fi

# Manifest patch: foreground-service permissions for MeshNodeService (targetSdk 34).
# FOREGROUND_SERVICE is required for any FGS; FOREGROUND_SERVICE_SPECIAL_USE is the
# type-specific grant matching the specialUse declaration above. Injected before
# the <application tag (uses-permission must be a direct child of <manifest>).
if [ -f "$MANIFEST" ] && ! grep -q 'android.permission.FOREGROUND_SERVICE_SPECIAL_USE' "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — FOREGROUND_SERVICE permissions"
    "$PY" - "$MANIFEST" <<'PY'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
perms = '''    <!-- Foreground service perms for MeshNodeService (injected by android/inject.sh) -->
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_SPECIAL_USE" />
'''
# Anchor on the bare "<application" opener (matches regardless of indent), same
# robust approach as the allowBackup patch below.
anchor = "<application"
if 'android.permission.FOREGROUND_SERVICE_SPECIAL_USE' in s:
    print("  perms already present")
elif anchor in s:
    s = s.replace(anchor, perms + anchor, 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  perms injected before <application>")
else:
    print("  no <application> tag found — skipped")
PY
else
    echo "[inject] manifest already has FOREGROUND_SERVICE perms (skip)"
fi

# Manifest patch: disable Android Auto Backup (SPEC-33 §13) so the OS never
# uploads EncryptedSharedPreferences (identity.key / LLM keys / broker JWT) to
# Google cloud backup. Cross-device backup is opt-in via the broker vault sync.
if [ -f "$MANIFEST" ] && ! grep -q 'android:allowBackup="false"' "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — allowBackup=false (SPEC-33 §13)"
    "$PY" - "$MANIFEST" <<'PY'
import sys, re
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
if 'android:allowBackup="false"' in s:
    print("  already disabled")
elif 'android:allowBackup="true"' in s:
    s = s.replace('android:allowBackup="true"', 'android:allowBackup="false"', 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  flipped allowBackup true→false")
elif "<application" in s:
    # No explicit attr — inject one right after the <application tag opener.
    s = s.replace("<application", '<application\n        android:allowBackup="false"', 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  injected allowBackup=false")
else:
    print("  no <application> tag found — skipped")
PY
else
    echo "[inject] manifest already has allowBackup=false (skip)"
fi

# Manifest patch: register the SPEC-34 §10E habit-chip Glance widget receiver.
if [ -f "$MANIFEST" ] && ! grep -q "HabitChipPaletteWidgetReceiver" "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — registering HabitChipPaletteWidgetReceiver"
    "$PY" - "$MANIFEST" <<'PY'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
receiver = '''
        <!-- SPEC-34 §10E habit-chip palette widget (injected by android/inject.sh) -->
        <receiver
            android:name=".HabitChipPaletteWidgetReceiver"
            android:exported="true"
            android:label="@string/habit_widget_description">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/habit_chip_palette_widget_info" />
        </receiver>
'''
anchor = "        <provider"
if "HabitChipPaletteWidgetReceiver" not in s and anchor in s:
    s = s.replace(anchor, receiver + "\n" + anchor, 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  manifest patched (widget receiver)")
else:
    print("  manifest already has widget receiver or anchor missing")
PY
else
    echo "[inject] manifest already registers widget receiver (skip)"
fi

# Manifest patch: register BootReceiver so the mesh node revives after reboot.
#
# WHY: on device reboot the OS tears down MeshNodeService (the persistent
# specialUse FGS) and pending WorkManager jobs need re-evaluation. BootReceiver
# listens for BOOT_COMPLETED (+ LOCKED_BOOT_COMPLETED) and best-effort
# re-schedules the upkeep worker + (re)starts the node FGS. exported=true is
# required: the boot broadcast originates from the system, not the app.
# (This is the REBOOT case only — the API31+ background non-boot FGS-start
# restriction is a separate FCM follow-up, not handled here.)
if [ -f "$MANIFEST" ] && ! grep -q 'android:name=".BootReceiver"' "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — registering BootReceiver"
    "$PY" - "$MANIFEST" <<'PY'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
receiver = '''
        <!-- Reboot revival of the mesh node (injected by android/inject.sh).
             REBOOT case only; API31+ background start is a separate FCM follow-up. -->
        <receiver
            android:name=".BootReceiver"
            android:exported="true"
            android:enabled="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
'''
anchor = "        <provider"
if 'android:name=".BootReceiver"' not in s and anchor in s:
    s = s.replace(anchor, receiver + "\n" + anchor, 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  manifest patched (BootReceiver)")
else:
    print("  manifest already has BootReceiver or anchor missing")
PY
else
    echo "[inject] manifest already registers BootReceiver (skip)"
fi

# Manifest patch: RECEIVE_BOOT_COMPLETED permission for BootReceiver. Required
# for the system to deliver BOOT_COMPLETED to the receiver above. Injected
# before the <application tag (uses-permission is a direct child of <manifest>).
if [ -f "$MANIFEST" ] && ! grep -q 'android.permission.RECEIVE_BOOT_COMPLETED' "$MANIFEST"; then
    echo "[inject] patching AndroidManifest — RECEIVE_BOOT_COMPLETED permission"
    "$PY" - "$MANIFEST" <<'PY'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
perm = '''    <!-- Reboot revival for BootReceiver (injected by android/inject.sh) -->
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
'''
anchor = "<application"
if 'android.permission.RECEIVE_BOOT_COMPLETED' in s:
    print("  perm already present")
elif anchor in s:
    s = s.replace(anchor, perm + anchor, 1)
    open(p, "w", encoding="utf-8").write(s)
    print("  perm injected before <application>")
else:
    print("  no <application> tag found — skipped")
PY
else
    echo "[inject] manifest already has RECEIVE_BOOT_COMPLETED perm (skip)"
fi

# Gradle patch: ensure Glance (widget) + WorkManager deps are present. The
# generated app/build.gradle.kts has a dependencies { } block; append ours once.
GRADLE="$HERE/../gen/android/app/build.gradle.kts"
if [ -f "$GRADLE" ] && ! grep -q "glance-appwidget" "$GRADLE"; then
    echo "[inject] patching build.gradle.kts — Glance + WorkManager deps"
    "$PY" - "$GRADLE" <<'PY'
import sys, re
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
deps = '''    // SPEC-34 §10E + WorkManager (injected by android/inject.sh)
    implementation("androidx.glance:glance-appwidget:1.1.1")
    implementation("androidx.work:work-runtime-ktx:2.9.1")
    // SPEC-12 §7.3 identity keystore: EncryptedSharedPreferences + MasterKey
    // (AndroidKeyStore-backed) for IdentityKeystore.kt (injected by android/inject.sh)
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
'''
m = re.search(r"dependencies\s*\{", s)
if "glance-appwidget" in s:
    print("  deps already present")
elif m:
    i = m.end()
    s = s[:i] + "\n" + deps + s[i:]
    open(p, "w", encoding="utf-8").write(s)
    print("  deps injected into dependencies { }")
else:
    print("  no dependencies { } block found — skipped (check build.gradle.kts)")
PY
else
    echo "[inject] build.gradle.kts already has Glance dep (skip)"
fi

# Gradle patch: Jetpack Glance widgets are @Composable, so the Android app module
# needs the Compose compiler enabled. The Tauri-generated project is a plain
# (non-Compose) app, so we turn it on here. Kotlin 1.9.25 (this project) pairs
# with Compose compiler extension 1.5.15. (Kotlin 2.0+ would use the separate
# org.jetbrains.kotlin.plugin.compose plugin instead — handled if/when Tauri bumps.)
if [ -f "$GRADLE" ] && ! grep -q "kotlinCompilerExtensionVersion" "$GRADLE"; then
    echo "[inject] patching build.gradle.kts — enable Compose compiler (for Glance)"
    "$PY" - "$GRADLE" <<'PY'
import sys, re
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
compose = '''
    // SPEC-34 §10E: Glance is Compose-based — enable the Compose compiler
    // (injected by android/inject.sh). Kotlin 1.9.25 -> compose compiler 1.5.15.
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }
'''
if "kotlinCompilerExtensionVersion" in s:
    print("  compose already enabled")
else:
    m = re.search(r"android\s*\{", s)
    if m:
        i = m.end()
        s = s[:i] + compose + s[i:]
        open(p, "w", encoding="utf-8").write(s)
        print("  compose buildFeatures + composeOptions injected")
    else:
        print("  no android { } block found — skipped")
PY
else
    echo "[inject] build.gradle.kts already enables Compose (skip)"
fi

echo "[inject] done. Custom Android code injected into gen/android."
