#!/usr/bin/env bash
# Build the phantom-mesh Tauri Android APK (the GUI app, not the Termux CLI).
#
# This is the reproducible wrapper for the sequence that must run in order:
#   tauri android init  →  android/inject.sh  →  tauri android build
# The middle step is essential: gen/android is gitignored and regenerated by
# `tauri android init`, so our tracked custom Kotlin (MainActivity +
# MeshNodeService + FocusQuickTile) and the SPEC-33 §11 manifest permissions
# only land via android/inject.sh. Skipping inject yields an APK with no
# foreground-service registration / perms — i.e. a node that can't run.
#
# (For the Termux ARM64 CLI tarball instead, see package-android.sh.)
#
# Usage:
#   ./scripts/package-android-apk.sh                 # debug, aarch64
#   ./scripts/package-android-apk.sh --release       # release build
#   ./scripts/package-android-apk.sh --target aarch64 --clean
#
# Requirements: Android SDK + NDK, Rust + android targets, Node deps installed.
#   NDK is located via ANDROID_NDK_HOME / ANDROID_NDK_ROOT, else the highest
#   version under $ANDROID_HOME/ndk (or the platform-default SDK locations).

set -euo pipefail

PROFILE="debug"
TARGET="aarch64"
CLEAN=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --release) PROFILE="release"; shift ;;
    --debug)   PROFILE="debug"; shift ;;
    --target)  TARGET="$2"; shift 2 ;;
    --clean)   CLEAN=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
APP="$REPO_ROOT/app"

# ── Locate NDK (honour env, else highest under known SDK roots) ───────────────
NDK_CANDIDATES=()
[[ -n "${ANDROID_NDK_HOME:-}" ]] && NDK_CANDIDATES+=("$ANDROID_NDK_HOME")
[[ -n "${ANDROID_NDK_ROOT:-}" ]] && NDK_CANDIDATES+=("$ANDROID_NDK_ROOT")
NDK_BASES=()
[[ -n "${ANDROID_HOME:-}"     ]] && NDK_BASES+=("${ANDROID_HOME}/ndk")
[[ -n "${ANDROID_SDK_ROOT:-}" ]] && NDK_BASES+=("${ANDROID_SDK_ROOT}/ndk")
[[ -n "${LOCALAPPDATA:-}"     ]] && NDK_BASES+=("${LOCALAPPDATA}/Android/Sdk/ndk")
NDK_BASES+=("${HOME}/Library/Android/sdk/ndk" "${HOME}/Android/Sdk/ndk")
for base in "${NDK_BASES[@]}"; do
  [[ -d "$base" ]] || continue
  pick=$(ls -1d "$base"/*/ 2>/dev/null | sort -V | tail -1 || true)
  [[ -n "$pick" ]] && NDK_CANDIDATES+=("${pick%/}")
done
NDK=""
for cand in "${NDK_CANDIDATES[@]}"; do
  [[ -d "$cand" ]] && { NDK="$cand"; break; }
done
[[ -z "$NDK" ]] && { echo "❌ Android NDK not found. Set ANDROID_NDK_HOME or install via sdkmanager 'ndk;<ver>'." >&2; exit 1; }
export NDK_HOME="$NDK" ANDROID_NDK_HOME="$NDK" ANDROID_NDK_ROOT="$NDK"
echo "◆ NDK: $NDK"

cd "$APP"
[[ -d node_modules ]] || { echo "◆ installing node deps …"; npm install; }

# ── 1. ensure gen/android (regenerate on --clean or if missing) ───────────────
if [[ "$CLEAN" == "1" ]]; then
  echo "◆ --clean: removing gen/android"
  rm -rf src-tauri/gen/android
fi
if [[ ! -d src-tauri/gen/android ]]; then
  echo "◆ tauri android init …"
  npm run tauri android init
fi

# ── 2. inject tracked custom Kotlin + SPEC-33 §11 manifest perms ──────────────
echo "◆ injecting custom Android code …"
bash src-tauri/android/inject.sh

# ── 3. build the APK ──────────────────────────────────────────────────────────
BUILD_ARGS=(--apk --target "$TARGET")
[[ "$PROFILE" == "debug" ]] && BUILD_ARGS+=(--debug)
echo "◆ tauri android build ${BUILD_ARGS[*]} …"
npm run tauri android build -- "${BUILD_ARGS[@]}"

# ── 4. report APK + sha256 ────────────────────────────────────────────────────
APK=$(find src-tauri/gen/android/app/build/outputs/apk -name '*.apk' -path "*${PROFILE}*" 2>/dev/null | sort | tail -1 || true)
if [[ -z "$APK" ]]; then
  echo "⚠  build finished but no ${PROFILE} APK found under gen/android/app/build/outputs/apk" >&2
  exit 1
fi
echo ""
echo "✓ APK: $APK"
echo "  size:   $(du -h "$APK" | cut -f1)"
if command -v sha256sum >/dev/null 2>&1; then
  echo "  sha256: $(sha256sum "$APK" | cut -d' ' -f1)"
fi
