#!/usr/bin/env bash
# setup-cloud-linux.sh — bootstrap a $5/mo Linux VPS as a phantom-mesh
# cluster execution container.
#
# Designed for a freshly-provisioned Ubuntu 22.04 / Debian 12 box from
# DigitalOcean / Linode / Hetzner / etc. Run as root or with sudo.
#
# What you get:
#   - Tailscale joined to your tailnet
#   - phantom binary on PATH
#   - phantom serve running as systemd unit (auto-restart, on by default)
#   - agents.toml with the cluster peers + node_name = $NODE_NAME
#
# What you do NOT get (left to you, since cloud machines vary):
#   - Specific repos cloned (the cloud node is meant as a pure execution
#     container — you push tasks to it via subagent({node}), not run
#     specific repo demos on it)
#   - GPU / CUDA setup (this VPS is for orchestration, not training)
#   - Any data persistence beyond ~/.phantom-mesh/
#
# Usage on a freshly-provisioned VPS:
#
#   curl -fsSL https://raw.githubusercontent.com/markl-a/phantom-mesh/main/scripts/setup-cloud-linux.sh \
#       | sudo NODE_NAME=cloud-vps-1 \
#              CLUSTER_SECRET=phantom-cluster-2026 \
#              TAILSCALE_AUTHKEY=tskey-... \
#              bash
#
# Idempotent. Safe to re-run.

set -euo pipefail

NODE_NAME="${NODE_NAME:-cloud-vps-$(hostname -s)}"
CLUSTER_SECRET="${CLUSTER_SECRET:-phantom-cluster-2026}"
TAILSCALE_AUTHKEY="${TAILSCALE_AUTHKEY:-}"
PHANTOM_RELEASE_URL="${PHANTOM_RELEASE_URL:-}"
SERVE_PORT="${SERVE_PORT:-7878}"

step()  { echo; echo "── $*"; }
ok()    { echo "  ✓ $*"; }
warn()  { echo "  ⚠ $*"; }
fail()  { echo "  ✗ $*" >&2; exit 1; }

step "0. Privilege check"
[ "$(id -u)" = "0" ] || fail "Run as root or with sudo"

step "1. apt deps"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl ca-certificates gnupg lsb-release git make python3 python3-pip
ok "base tools installed"

step "2. Tailscale"
if ! command -v tailscale >/dev/null 2>&1; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi
if ! tailscale status >/dev/null 2>&1; then
    if [ -n "$TAILSCALE_AUTHKEY" ]; then
        tailscale up --authkey "$TAILSCALE_AUTHKEY" --hostname "$NODE_NAME"
    else
        warn "Tailscale not authed yet. Run: tailscale up --authkey tskey-..."
    fi
fi
ok "tailscale: $(tailscale status 2>&1 | head -1 || echo unknown)"

step "3. phantom binary"
PHANTOM_BIN="/usr/local/bin/phantom"
if [ -x "$PHANTOM_BIN" ]; then
    ok "phantom already at $PHANTOM_BIN: $($PHANTOM_BIN --version | head -1)"
else
    if [ -z "$PHANTOM_RELEASE_URL" ]; then
        ARCH=$(uname -m)
        case "$ARCH" in
            x86_64|amd64)   PHANTOM_RELEASE_URL="https://github.com/markl-a/phantom-mesh/releases/latest/download/phantom-x86_64-unknown-linux" ;;
            aarch64|arm64)  PHANTOM_RELEASE_URL="https://github.com/markl-a/phantom-mesh/releases/latest/download/phantom-aarch64-unknown-linux" ;;
            *) fail "unknown arch $ARCH; set PHANTOM_RELEASE_URL=..." ;;
        esac
    fi
    echo "  downloading $PHANTOM_RELEASE_URL"
    curl -fsSL "$PHANTOM_RELEASE_URL" -o "$PHANTOM_BIN"
    chmod +x "$PHANTOM_BIN"
    ok "installed to $PHANTOM_BIN"
fi

step "4. agents.toml"
PHANTOM_HOME="${PHANTOM_HOME:-/root/.phantom-mesh}"
mkdir -p "$PHANTOM_HOME"
CFG="$PHANTOM_HOME/agents.toml"
if [ ! -f "$CFG" ]; then
    cat > "$CFG" <<EOF
# phantom-mesh agents.toml — generated by setup-cloud-linux.sh

[core]
host = "0.0.0.0"
port = $SERVE_PORT

[providers.anthropic]
type        = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"

[agent.master]
provider     = "anthropic"
tools        = ["shell", "file_read", "file_edit", "content_search",
                "git_status", "git_diff", "task"]
instructions = "You are phantom on a cloud Linux execution container. Be terse."

[cluster]
node_name      = "$NODE_NAME"
cluster_secret = "$CLUSTER_SECRET"
peers = [
  "http://100.106.176.125:7878",   # acer
  "http://100.107.205.98:7878",    # ayaneo
  "http://100.87.70.65:7879",      # yoyogood (Z13)
  "http://100.87.93.58:7878",      # mac-coordinator
]
EOF
    ok "wrote $CFG"
else
    ok "$CFG exists (NOT overwriting)"
fi

step "5. systemd unit"
SVC=/etc/systemd/system/phantom-serve.service
if [ ! -f "$SVC" ]; then
    cat > "$SVC" <<EOF
[Unit]
Description=phantom-mesh serve
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
Environment=PHANTOM_HOME=$PHANTOM_HOME
EnvironmentFile=-/etc/phantom-mesh/env
ExecStart=$PHANTOM_BIN serve --port $SERVE_PORT
Restart=on-failure
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable phantom-serve.service
    ok "wrote $SVC + enabled"
else
    ok "$SVC exists"
fi
mkdir -p /etc/phantom-mesh
[ -f /etc/phantom-mesh/env ] || cat > /etc/phantom-mesh/env <<'EOF'
# put your provider keys here (chmod 600). e.g.:
# ANTHROPIC_API_KEY=sk-ant-...
# GROQ_API_KEY=gsk_...
EOF
chmod 600 /etc/phantom-mesh/env

step "6. start"
systemctl restart phantom-serve.service
sleep 2
if systemctl is-active --quiet phantom-serve.service; then
    ok "phantom-serve.service active"
else
    fail "phantom-serve.service failed to start — see: journalctl -u phantom-serve"
fi

step "7. verify"
TS_IP=$(tailscale ip -4 2>&1 | head -1 || echo "")
echo "  /healthz → $(curl -s "http://127.0.0.1:$SERVE_PORT/healthz" || echo 'unreachable')"
echo "  tailscale ip: ${TS_IP:-(not joined yet — run: tailscale up --authkey ...)}"

echo
echo "━━━ DONE ━━━"
echo "Add this peer to other nodes' agents.toml:"
echo "  \"http://${TS_IP}:${SERVE_PORT}\",   # $NODE_NAME"
echo
echo "From any other peer, confirm dispatch works:"
echo "  phantom run --node $NODE_NAME 'echo hi from cloud'"
