#!/bin/bash
set -euo pipefail

# spectyn-mesh Tailscale mesh setup
# Configures this machine as a worker node pointing to a Mac coordinator.
#
# Usage:
#   bash setup-tailscale-mesh.sh <MAC_TAILSCALE_IP> <CLUSTER_SECRET>
#
# Arguments:
#   MAC_TAILSCALE_IP  — Tailscale IP of the Mac coordinator (from 'tailscale ip -4' on Mac)
#   CLUSTER_SECRET    — Shared cluster secret (must match all nodes)
#
# Example:
#   bash setup-tailscale-mesh.sh 100.64.0.1 my-super-secret

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <MAC_TAILSCALE_IP> <CLUSTER_SECRET>"
  echo ""
  echo "Example: $0 100.64.0.1 my-super-secret"
  echo ""
  echo "To find your Mac's Tailscale IP: run 'tailscale ip -4' on the Mac."
  exit 1
fi

MAC_TAILSCALE_IP="$1"
CLUSTER_SECRET="$2"

CONFIG_DIR="${HOME}/.spectyn-mesh"
CONFIG_FILE="${CONFIG_DIR}/agents.toml"

# Detect node name from hostname, stripped to something friendly
NODE_NAME="${NODE_NAME:-$(hostname -s | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')}"
if [[ -z "$NODE_NAME" ]]; then
  NODE_NAME="worker-node"
fi

# Get this machine's Tailscale IP (best-effort; non-fatal if not yet configured)
THIS_TAILSCALE_IP=""
if which tailscale &>/dev/null; then
  THIS_TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || true)
fi

echo "==> spectyn-mesh Tailscale mesh setup"
echo "    Node name:       $NODE_NAME"
echo "    Mac coordinator: $MAC_TAILSCALE_IP"
if [[ -n "$THIS_TAILSCALE_IP" ]]; then
  echo "    This node IP:    $THIS_TAILSCALE_IP"
else
  echo "    This node IP:    (not detected — run 'tailscale ip -4' after connecting)"
fi
echo ""

# Create config directory
mkdir -p "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
  echo "==> Backing up existing config to ${CONFIG_FILE}.bak"
  cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
fi

echo "==> Writing worker config to $CONFIG_FILE"
cat > "$CONFIG_FILE" << EOF
# Spectyn Mesh — Worker Node Config
# ====================================
# Auto-generated by setup-tailscale-mesh.sh
# Node: $NODE_NAME
# Mac coordinator: $MAC_TAILSCALE_IP

[core]
host = "0.0.0.0"        # listen on all interfaces so the coordinator can reach this node
port = 7878
node_name = "$NODE_NAME"

# ── Providers ─────────────────────────────────────────────────────────────────
# Primary: local Ollama (free, private).  Fallback: Anthropic API.

[providers.ollama]
type = "openai_compat"
url = "http://localhost:11434/v1"
api_key = "ollama"
default_model = "qwen2.5-coder:14b"

[providers.anthropic]
type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-haiku-4-5"

# ── Cluster ───────────────────────────────────────────────────────────────────

[cluster]
node_name = "$NODE_NAME"
cluster_secret = "$CLUSTER_SECRET"
peers = [
  "http://${MAC_TAILSCALE_IP}:7878",   # Mac coordinator
]

# ── Master agent ───────────────────────────────────────────────────────────────

[agent.master]
provider = "ollama"
model = "qwen2.5-coder:14b"
tools = [
  "shell",
  "file_read",
  "file_write",
  "file_edit",
  "content_search",
  "glob_search",
  "memory_store",
  "memory_recall",
]
instructions = "You are a spectyn-mesh worker node. Execute tasks assigned by the coordinator efficiently. Focus on shell and file operations. Be concise."
EOF

echo ""
echo "==> Done! Config written to $CONFIG_FILE"
echo ""
echo "==> NEXT STEPS:"
echo ""
echo "  1. Start the daemon on this machine:"
echo "     spectyn-mesh daemon --config $CONFIG_FILE"
echo ""
echo "  2. On your Mac coordinator, add this node as a peer."
echo "     Edit your Mac's agents.toml and add to [cluster].peers:"
if [[ -n "$THIS_TAILSCALE_IP" ]]; then
  echo "       \"http://${THIS_TAILSCALE_IP}:7878\",   # $NODE_NAME"
else
  echo "       \"http://<THIS_NODE_TAILSCALE_IP>:7878\",   # $NODE_NAME"
  echo "     (run 'tailscale ip -4' on this machine to get the IP)"
fi
echo ""
echo "  3. Restart the Mac coordinator daemon to pick up the new peer."
echo ""
