#!/usr/bin/env bash
# gen-status.sh — 產生 docs/status.md，列出所有 active SPEC 的 4 件套覆蓋
#
# 4 件套定義（C 階段尚未到位的會標 ✗、未來 B 階段補）：
#   doc      — docs/spec/ 有 spec 文件（archive 不算）
#   code     — core/src/、app/src/、app/src-tauri/ 內 grep 到 spec id
#   test     — tests-e2e/、core/tests/、app/e2e/ 內 grep 到 spec id
#   flow     — docs/flow/<spec-slug>.md 存在（C 階段建立、目前皆 ✗）
#
# Usage: ./scripts/coord/gen-status.sh  → writes docs/status.md
# Reporting script; don't use `set -e` since grep returning empty is normal here.
set -u

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

OUT="docs/status.md"
TMP=$(mktemp)
TS=$(date '+%Y-%m-%d %H:%M:%S')

# ── 1. 蒐集 active SPECs（排除 archive、template、INDEX） ─────────────────
ACTIVE_SPECS=$(find docs -type f -name "SPEC-*.md" \
    -not -path "*/history/*" \
    -not -name "SPEC-TEMPLATE.md" \
    -not -name "SPEC-TO-CODE-PLAYBOOK.md" \
    -not -name "SPEC-00-INDEX.md" 2>/dev/null | sort)

# ── 2. 一次性 dump SPEC refs（避免 N 次 rg） ──────────────────────────────
rg -o "SPEC-[0-9]+" core/src/ app/src/ app/src-tauri/ 2>/dev/null \
    | sed 's|^.*:||' | sort -u > "$TMP.code"
rg -o "SPEC-[0-9]+" tests-e2e/ core/tests/ app/e2e/ 2>/dev/null \
    | sed 's|^.*:||' | sort -u > "$TMP.test"

# ── 3. 產 markdown ────────────────────────────────────────────────────────
{
    echo "# Spectyn-mesh — SPEC coverage status"
    echo ""
    echo "_Auto-generated by \`scripts/coord/gen-status.sh\` at $TS. Do not hand-edit; re-run script._"
    echo ""
    echo "**4 件套覆蓋**：doc / code / test / flow（flow 在 C 階段建立 \`docs/flow/\` 後才有）"
    echo ""
    echo "| SPEC | Title | Doc | Code | Test | Flow | Status |"
    echo "|------|-------|-----|------|------|------|--------|"

    TOTAL=0; FULL=0; CODE_NOT_TEST=0; ZOMBIE=0
    while IFS= read -r f; do
        TOTAL=$((TOTAL+1))
        slug=$(basename "$f" .md)
        spec_id=$(echo "$slug" | grep -oE "^SPEC-[0-9]+")
        title=$(grep -m1 "^# " "$f" 2>/dev/null | sed 's/^# *//' | sed 's/SPEC-[0-9]* *[·•] *//' | head -c 60)
        status=$(grep -E "^\| Status" "$f" 2>/dev/null | head -1 | sed -E 's/.*`([^`]*)`.*/\1/' | head -c 12)
        [ -z "$status" ] && status="(no frontmatter)"

        # doc 永遠 ✓（檔案存在才會在 list 裡）
        d="✓"
        # code/test：spec id 在 dump 內
        grep -qx "$spec_id" "$TMP.code" && c="✓" || c="✗"
        grep -qx "$spec_id" "$TMP.test" && t="✓" || t="✗"
        # flow：docs/flow/<spec-slug>.md 存在?
        flow_slug=$(echo "$slug" | sed -E 's/SPEC-[0-9]+-//')
        [ -f "docs/flow/${flow_slug}.md" ] && fl="✓" || fl="✗"

        [ "$c" = "✓" ] && [ "$t" = "✓" ] && [ "$fl" = "✓" ] && FULL=$((FULL+1))
        [ "$c" = "✓" ] && [ "$t" = "✗" ] && CODE_NOT_TEST=$((CODE_NOT_TEST+1))
        [ "$c" = "✗" ] && ZOMBIE=$((ZOMBIE+1))

        echo "| $spec_id | $title | $d | $c | $t | $fl | $status |"
    done <<< "$ACTIVE_SPECS"

    echo ""
    echo "## 統計"
    echo ""
    echo "- **Active SPECs**: $TOTAL"
    echo "- **完整 4/4** (doc + code + test + flow): $FULL"
    echo "- **有 code、缺 test** (定時炸彈): $CODE_NOT_TEST"
    echo "- **zombie spec** (有 doc、無 code): $ZOMBIE"
    echo ""
    echo "## 圖例"
    echo ""
    echo "- ✓ = 該件套存在"
    echo "- ✗ = 缺、要補"
    echo "- \`(no frontmatter)\` = SPEC 文件沒按 SPEC-TEMPLATE 寫 Status 表格"
    echo ""
    echo "## 怎麼用此頁"
    echo ""
    echo "1. **session boot** 第一件事讀本頁 + \`.ai-shared/BROADCAST.md\`"
    echo "2. 找 \`code=✓ test=✗\` 的列、那是你可以馬上補 e2e 的高價值工"
    echo "3. \`code=✗\` 但 status=\`live\` 的列、那是 zombie 要 archive 或補 impl"
    echo "4. 改完任何 SPEC / 補完 test → 重跑此腳本 + commit"
} > "$OUT"

rm -f "$TMP" "$TMP.code" "$TMP.test"
echo "✓ wrote $OUT (TOTAL=$TOTAL, FULL=$FULL, CODE_NOT_TEST=$CODE_NOT_TEST, ZOMBIE=$ZOMBIE)"
