pub mod secrets;
pub mod autonomy;
pub mod roles;
pub mod privacy;
pub mod key_vault;
pub mod key_sync;
pub mod node_identity;
pub mod cluster_auth;
pub mod key_export;
pub use secrets::SecretManager;
pub use autonomy::AutonomyLevel;
pub use roles::{Role, RoleRegistry};
pub use privacy::{PrivacyGuard, PrivacyConfig, PrivacyTier};
pub use key_vault::{KeyStore, LocalKeyVault, KeyMeta, KeyPermission, KeyVaultError};
pub use key_sync::{KeySyncServer, KeySyncClient, KeySyncMessage, KeySyncError};
pub use node_identity::NodeIdentity;
pub use cluster_auth::{ClusterAuth, AuthHeaders, AuthError};
pub use key_export::{PairingBundle, PairingData, PairingError};
