#!/bin/bash
set -euo pipefail

# spectyn-mesh GCP deployment script
# Usage: bash deploy-gcp.sh [--node-name NAME] [--port PORT]
#
# Environment variables (all optional, override defaults):
#   GITHUB_REPO      — GitHub repo slug, default: markl-a/spectyn-mesh
#   CLUSTER_SECRET   — Shared cluster secret (must match all nodes)
#   NODE_NAME        — Name for this node, default: gcp-cloud
#   PORT             — Port to listen on, default: 7878

GITHUB_REPO="${GITHUB_REPO:-markl-a/spectyn-mesh}"
CLUSTER_SECRET="${CLUSTER_SECRET:-CHANGE_ME_SHARED_SECRET}"
NODE_NAME=${NODE_NAME:-"gcp-cloud"}
PORT=${PORT:-7878}
INSTALL_DIR="/opt/spectyn-mesh"
SERVICE_USER="spectyn"
ARCH=$(uname -m)

echo "==> spectyn-mesh GCP deployment"
echo "    Node: $NODE_NAME | Port: $PORT | Arch: $ARCH"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --node-name) NODE_NAME="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Detect binary name based on arch
if [[ "$ARCH" == "aarch64" ]]; then
  BINARY_SUFFIX="aarch64-unknown-linux-gnu"
else
  BINARY_SUFFIX="x86_64-unknown-linux-gnu"
fi

# Create service user
if ! id "$SERVICE_USER" &>/dev/null; then
  sudo useradd -r -s /bin/false -d "$INSTALL_DIR" "$SERVICE_USER"
  echo "    Created user: $SERVICE_USER"
fi

# Create directories
sudo mkdir -p "$INSTALL_DIR"
sudo mkdir -p "/home/$SERVICE_USER/.spectyn-mesh"
sudo chown "$SERVICE_USER:$SERVICE_USER" "/home/$SERVICE_USER/.spectyn-mesh"

# Check / install Tailscale
echo "==> Checking Tailscale..."
if ! which tailscale &>/dev/null; then
  echo "    Tailscale not found — installing..."
  apt-get install -y tailscale 2>/dev/null || {
    curl -fsSL https://tailscale.com/install.sh | sh
  }
else
  echo "    Tailscale already installed: $(tailscale version 2>/dev/null | head -1)"
fi
echo ""
echo "==> TAILSCALE SETUP REQUIRED:"
echo "    Run: sudo tailscale up"
echo "    Then: tailscale ip -4   (note this GCP node's Tailscale IP)"
echo "    On your Mac coordinator, add this IP to peers[] in agents.toml"
echo ""

# Load the SHA256 + HTTPS verification helper.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd 2>/dev/null || echo "")"
VERIFY_HELPER=""
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/../_verify-download.sh" ]; then
    VERIFY_HELPER="$SCRIPT_DIR/../_verify-download.sh"
else
    VERIFY_HELPER="$(mktemp -t spectyn-verify.XXXXXX)"
    HELPER_URL="https://raw.githubusercontent.com/${GITHUB_REPO}/main/scripts/_verify-download.sh"
    if ! curl -fsSL --max-time 10 "$HELPER_URL" -o "$VERIFY_HELPER"; then
        echo "ERROR: Could not load $HELPER_URL — refusing to install unverified binary" >&2
        exit 1
    fi
fi
# shellcheck disable=SC1090
. "$VERIFY_HELPER"

# Download latest release binary
LATEST=$(curl -s "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" \
  | grep "browser_download_url.*$BINARY_SUFFIX" | cut -d'"' -f4)

if [[ -z "$LATEST" ]]; then
  echo "ERROR: Could not find binary for $BINARY_SUFFIX"
  echo "       Please manually place spectyn-mesh binary at $INSTALL_DIR/spectyn-mesh"
  exit 1
fi

# Enforce HTTPS + SHA256-verify the binary BEFORE chmod +x.
require_https "$LATEST" || exit 1

echo "==> Downloading binary from $LATEST"
# Download to a user-writable tmp first so verify_sha256 can rm-on-mismatch
# without needing sudo. Move into place only after verification succeeds.
TMP_BIN="$(mktemp -t spectyn-mesh.XXXXXX)"
trap 'rm -f "$TMP_BIN" "${VERIFY_HELPER:-}"' EXIT
curl -fsSL "$LATEST" -o "$TMP_BIN"
verify_sha256 "$TMP_BIN" "$LATEST"
sudo install -m 0755 "$TMP_BIN" "$INSTALL_DIR/spectyn-mesh"
rm -f "$TMP_BIN"
trap - EXIT

# Create config
if [[ ! -f "/home/$SERVICE_USER/.spectyn-mesh/agents.toml" ]]; then
  echo "==> Creating default config at /home/$SERVICE_USER/.spectyn-mesh/agents.toml"
  sudo tee "/home/$SERVICE_USER/.spectyn-mesh/agents.toml" > /dev/null << EOF
# Spectyn Mesh — GCP Cloud Node Config
# ======================================
# Auto-generated by deploy-gcp.sh
#
# TAILSCALE SETUP:
#   1. Run: sudo tailscale up
#   2. Get this node's Tailscale IP: tailscale ip -4
#   3. On your Mac coordinator, add this node's IP to the peers[] list in agents.toml
#   4. Set MAC_TAILSCALE_IP below to your Mac coordinator's Tailscale IP
#      (run 'tailscale ip -4' on the Mac to find it)

[core]
host = "0.0.0.0"   # must listen on all interfaces for Tailscale mesh access
port = $PORT
node_name = "$NODE_NAME"

# ── Providers ─────────────────────────────────────────────────────────────────

[providers.anthropic]
type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-haiku-4-5"

# ── Cluster ───────────────────────────────────────────────────────────────────
# Set peers to the Tailscale IP of your Mac coordinator.
# Replace MAC_TAILSCALE_IP with the output of 'tailscale ip -4' on the Mac.

[cluster]
node_name = "$NODE_NAME"
cluster_secret = "${CLUSTER_SECRET}"
peers = ["http://MAC_TAILSCALE_IP:7878"]   # replace with actual Mac Tailscale IP

# ── Telegram bot ──────────────────────────────────────────────────────────────
# The cloud node is the Telegram gateway for the entire mesh.

[telegram]
bot_token_env = "TELEGRAM_BOT_TOKEN"
allowed_users = []
agent = "master"

# ── Master agent ───────────────────────────────────────────────────────────────

[agent.master]
provider = "anthropic"
model = "claude-haiku-4-5"
instructions = "You are a spectyn-mesh cloud node agent. Handle Telegram messages, relay tasks, and execute work efficiently. Always respond in the user's language."
tools = ["shell", "file_read", "file_write", "file_edit", "content_search", "glob_search", "web_search", "git_status", "git_diff", "git_log", "memory_store", "memory_recall"]
EOF
  sudo chown "$SERVICE_USER:$SERVICE_USER" "/home/$SERVICE_USER/.spectyn-mesh/agents.toml"
fi

# Install systemd service
sudo tee "/etc/systemd/system/spectyn-mesh.service" > /dev/null << EOF
[Unit]
Description=Spectyn Mesh AI Agent Daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=/home/$SERVICE_USER
ExecStart=$INSTALL_DIR/spectyn-mesh daemon --host 0.0.0.0 --port $PORT
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
Environment=HOME=/home/$SERVICE_USER
EnvironmentFile=-/home/$SERVICE_USER/.spectyn-mesh/env

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable spectyn-mesh
sudo systemctl start spectyn-mesh

echo ""
echo "==> spectyn-mesh deployed!"
echo "    Status: sudo systemctl status spectyn-mesh"
echo "    Logs:   sudo journalctl -u spectyn-mesh -f"
echo "    Health: curl http://localhost:$PORT/health"
echo ""
echo "==> Next steps:"
echo "    1. Run:  sudo tailscale up"
echo "    2. Get this node's Tailscale IP:  tailscale ip -4"
echo "    3. Edit  /home/$SERVICE_USER/.spectyn-mesh/agents.toml"
echo "       - Replace MAC_TAILSCALE_IP with your Mac coordinator's Tailscale IP"
echo "       - Set cluster_secret to match all other nodes"
echo "    4. Add API keys to /home/$SERVICE_USER/.spectyn-mesh/env"
echo "       - ANTHROPIC_API_KEY=sk-ant-..."
echo "       - TELEGRAM_BOT_TOKEN=..."
echo "    5. sudo systemctl restart spectyn-mesh"
echo "    6. Health check: curl http://localhost:$PORT/health"
