//! DSPy-style prompt evolution system.
//!
//! Uses trajectory data (from `trajectory.rs`) to automatically optimize
//! Hand phase `system_prompt` strings. The optimizer:
//!
//! 1. Collects good/bad examples from historical trajectory data
//! 2. Asks an LLM to analyze patterns and generate improved prompt variants
//! 3. Uses LLM-as-Judge to score each variant against test examples
//! 4. Returns the best improvement (or signals no improvement found)
//!
//! Inspired by DSPy MIPROv2 and OpenAI GEPA prompt optimizers.

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use tracing::{debug, info, warn};

use crate::llm_router::{ChatMessage, LlmRouter};
use crate::trajectory::TrajectoryEntry;

// ── Constants: Meta-Prompts ──────────────────────────────────────────────────

/// System prompt for the LLM that generates improved prompt variants.
/// The user message will contain the current prompt, good examples, and bad examples.
const GENERATE_VARIANTS_PROMPT: &str = r#"You are an expert prompt engineer specializing in optimizing system prompts for AI agents.

Your task: Given a current system prompt and examples of good vs bad outputs it produced, generate improved system prompt variants.

Analysis process:
1. Study the GOOD examples — what patterns made these outputs succeed?
2. Study the BAD examples — what patterns caused these outputs to fail?
3. Identify the gap between the current prompt's instructions and the desired behavior.
4. Generate improved prompt variants that:
   - Reinforce patterns seen in good outputs
   - Add guardrails against patterns seen in bad outputs
   - Are specific and actionable (avoid vague instructions)
   - Preserve the core intent of the original prompt

Output format: Return a JSON array of prompt strings, one per variant.
Example: ["Improved prompt variant 1...", "Improved prompt variant 2...", "Improved prompt variant 3..."]

IMPORTANT:
- Each variant should be a complete system prompt (not a diff or partial edit).
- Keep variants diverse — try different approaches (more structure, more examples, different tone).
- Do NOT include the analysis in your output — only the JSON array of prompts.
- Respond with ONLY the JSON array, no markdown code blocks."#;

/// System prompt for the LLM that evaluates prompt variants.
/// The user message will contain the variant prompt and test examples.
const EVALUATE_VARIANT_PROMPT: &str = r#"You are a prompt quality evaluator. Your job is to predict how well a given system prompt would perform on a set of tasks.

For each test example, assess whether the system prompt's instructions would likely guide an LLM to produce output of similar or better quality than the reference good output.

Scoring criteria:
- 5: The prompt would almost certainly produce excellent output for this example
- 4: The prompt would likely produce good output
- 3: The prompt might produce acceptable output
- 2: The prompt would likely produce poor output
- 1: The prompt would almost certainly fail on this example

You MUST respond with ONLY a JSON object in this exact format:
{"scores": [<score1>, <score2>, ...], "reasoning": "<brief overall assessment>"}

Where each score corresponds to one test example in order.
Do NOT include markdown code blocks — just the raw JSON."#;

// ── Types ────────────────────────────────────────────────────────────────────

/// Result of a prompt optimization attempt.
#[derive(Debug, Clone, Serialize)]
pub enum OptimizationResult {
    /// A better prompt was found.
    Improved {
        new_prompt: String,
        score_delta: f64,
        reasoning: String,
    },
    /// No variant outperformed the current prompt.
    NoImprovement {
        current_score: f64,
    },
    /// Not enough trajectory data to run optimization.
    InsufficientData {
        available: usize,
        needed: usize,
    },
    /// An error occurred during optimization.
    Error(String),
}

/// A candidate prompt generated by the optimizer.
#[derive(Debug, Clone, Serialize)]
pub struct PromptCandidate {
    pub prompt: String,
    pub score: f64,
    pub reasoning: String,
}

/// Configuration for the prompt optimizer.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct OptimizationConfig {
    /// Minimum number of trajectory entries required to attempt optimization.
    #[serde(default = "default_min_trajectories")]
    pub min_trajectories: usize,
    /// Number of prompt variants to generate per optimization run.
    #[serde(default = "default_variants_to_generate")]
    pub variants_to_generate: usize,
    /// Quality score >= this threshold counts as a "good" example.
    #[serde(default = "default_good_threshold")]
    pub good_threshold: u8,
    /// Quality score <= this threshold counts as a "bad" example.
    #[serde(default = "default_bad_threshold")]
    pub bad_threshold: u8,
}

fn default_min_trajectories() -> usize { 10 }
fn default_variants_to_generate() -> usize { 3 }
fn default_good_threshold() -> u8 { 4 }
fn default_bad_threshold() -> u8 { 2 }

impl Default for OptimizationConfig {
    fn default() -> Self {
        Self {
            min_trajectories: default_min_trajectories(),
            variants_to_generate: default_variants_to_generate(),
            good_threshold: default_good_threshold(),
            bad_threshold: default_bad_threshold(),
        }
    }
}

// ── PromptOptimizer ──────────────────────────────────────────────────────────

/// DSPy-style prompt optimizer that uses trajectory data to evolve system prompts.
pub struct PromptOptimizer {
    config: OptimizationConfig,
}

impl PromptOptimizer {
    /// Create a new PromptOptimizer with the given configuration.
    pub fn new(config: OptimizationConfig) -> Self {
        Self { config }
    }

    /// Create a PromptOptimizer with default configuration.
    pub fn default() -> Self {
        Self::new(OptimizationConfig::default())
    }

    /// Optimize a Hand phase's system prompt using trajectory data.
    ///
    /// # Arguments
    /// - `hand_name`: Name of the Hand workflow (for logging).
    /// - `phase_name`: Name of the phase within the Hand (for logging).
    /// - `current_prompt`: The current system_prompt text to optimize.
    /// - `trajectories`: Pre-fetched trajectory entries from `TrajectoryLogger`.
    /// - `router`: LLM router for generating and evaluating variants.
    ///
    /// # Returns
    /// An `OptimizationResult` indicating whether an improvement was found.
    pub async fn optimize_phase(
        &self,
        hand_name: &str,
        phase_name: &str,
        current_prompt: &str,
        trajectories: &[TrajectoryEntry],
        router: &LlmRouter,
    ) -> Result<OptimizationResult> {
        info!(
            "prompt_optimizer: starting optimization for {}/{} ({} trajectories)",
            hand_name, phase_name, trajectories.len()
        );

        // (a) Check if enough trajectories
        if trajectories.len() < self.config.min_trajectories {
            info!(
                "prompt_optimizer: insufficient data for {}/{} — have {}, need {}",
                hand_name, phase_name, trajectories.len(), self.config.min_trajectories
            );
            return Ok(OptimizationResult::InsufficientData {
                available: trajectories.len(),
                needed: self.config.min_trajectories,
            });
        }

        // (b) Split into good and bad examples
        let good_examples: Vec<(String, String)> = trajectories
            .iter()
            .filter(|t| {
                t.quality_score
                    .map(|s| s >= self.config.good_threshold)
                    .unwrap_or(false)
            })
            .map(|t| (t.prompt.clone(), t.output.clone()))
            .collect();

        let bad_examples: Vec<(String, String)> = trajectories
            .iter()
            .filter(|t| {
                t.quality_score
                    .map(|s| s <= self.config.bad_threshold)
                    .unwrap_or(false)
            })
            .map(|t| (t.prompt.clone(), t.output.clone()))
            .collect();

        debug!(
            "prompt_optimizer: {}/{} — {} good, {} bad examples",
            hand_name, phase_name, good_examples.len(), bad_examples.len()
        );

        // (c) Need at least 1 good and 1 bad example to learn from contrast
        if good_examples.is_empty() || bad_examples.is_empty() {
            let scored_count = good_examples.len() + bad_examples.len();
            info!(
                "prompt_optimizer: not enough contrast for {}/{} — {} good, {} bad (need >= 1 each)",
                hand_name, phase_name, good_examples.len(), bad_examples.len()
            );
            return Ok(OptimizationResult::InsufficientData {
                available: scored_count,
                needed: 2, // at least 1 good + 1 bad
            });
        }

        // (d) Generate variant prompts
        let variants = match self
            .generate_variants(current_prompt, &good_examples, &bad_examples, router)
            .await
        {
            Ok(v) => v,
            Err(e) => {
                warn!("prompt_optimizer: variant generation failed: {}", e);
                return Ok(OptimizationResult::Error(format!(
                    "Failed to generate variants: {}",
                    e
                )));
            }
        };

        if variants.is_empty() {
            warn!("prompt_optimizer: no variants generated for {}/{}", hand_name, phase_name);
            return Ok(OptimizationResult::Error(
                "LLM returned no valid prompt variants".to_string(),
            ));
        }

        info!(
            "prompt_optimizer: generated {} variants for {}/{}",
            variants.len(), hand_name, phase_name
        );

        // Use good examples as test set (we want the variant to reproduce good-quality outputs)
        let test_examples: Vec<(String, String)> = good_examples
            .iter()
            .take(5) // cap test set size to keep evaluation fast
            .cloned()
            .collect();

        // (e) Evaluate each variant
        let mut candidates: Vec<PromptCandidate> = Vec::new();
        for (i, variant) in variants.iter().enumerate() {
            match self.evaluate_variant(variant, &test_examples, router).await {
                Ok(score) => {
                    debug!(
                        "prompt_optimizer: variant {} scored {:.2} for {}/{}",
                        i + 1, score, hand_name, phase_name
                    );
                    candidates.push(PromptCandidate {
                        prompt: variant.clone(),
                        score,
                        reasoning: format!("Variant {} of {}", i + 1, variants.len()),
                    });
                }
                Err(e) => {
                    warn!(
                        "prompt_optimizer: failed to evaluate variant {}: {}",
                        i + 1, e
                    );
                }
            }
        }

        if candidates.is_empty() {
            return Ok(OptimizationResult::Error(
                "All variant evaluations failed".to_string(),
            ));
        }

        // (f) Compare best candidate vs current score
        let current_score = Self::estimate_current_score(trajectories);

        // Find the best candidate
        let best = candidates
            .iter()
            .max_by(|a, b| a.score.partial_cmp(&b.score).unwrap_or(std::cmp::Ordering::Equal))
            .unwrap(); // safe: candidates is non-empty

        let score_delta = best.score - current_score;

        info!(
            "prompt_optimizer: {}/{} — current={:.2}, best_variant={:.2}, delta={:+.2}",
            hand_name, phase_name, current_score, best.score, score_delta
        );

        // (g) Return Improved or NoImprovement
        if score_delta > 0.0 {
            Ok(OptimizationResult::Improved {
                new_prompt: best.prompt.clone(),
                score_delta,
                reasoning: format!(
                    "Best variant scored {:.2} vs current {:.2} (delta: {:+.2}). {}",
                    best.score, current_score, score_delta, best.reasoning
                ),
            })
        } else {
            Ok(OptimizationResult::NoImprovement {
                current_score,
            })
        }
    }

    /// Generate N prompt variant candidates from the LLM.
    ///
    /// Uses the meta-prompt `GENERATE_VARIANTS_PROMPT` to ask an LLM to analyze
    /// good vs bad output patterns and produce improved system_prompt variants.
    async fn generate_variants(
        &self,
        current_prompt: &str,
        good_examples: &[(String, String)],
        bad_examples: &[(String, String)],
        router: &LlmRouter,
    ) -> Result<Vec<String>> {
        // Format good examples (cap at 3 to fit context)
        let good_section = good_examples
            .iter()
            .take(3)
            .enumerate()
            .map(|(i, (input, output))| {
                format!(
                    "### Good Example {}\nInput: {}\nOutput: {}",
                    i + 1,
                    truncate(input, 500),
                    truncate(output, 1000)
                )
            })
            .collect::<Vec<_>>()
            .join("\n\n");

        // Format bad examples (cap at 3)
        let bad_section = bad_examples
            .iter()
            .take(3)
            .enumerate()
            .map(|(i, (input, output))| {
                format!(
                    "### Bad Example {}\nInput: {}\nOutput: {}",
                    i + 1,
                    truncate(input, 500),
                    truncate(output, 1000)
                )
            })
            .collect::<Vec<_>>()
            .join("\n\n");

        let user_message = format!(
            "## Current System Prompt\n{}\n\n\
             ## Good Outputs (quality >= {})\n{}\n\n\
             ## Bad Outputs (quality <= {})\n{}\n\n\
             Generate exactly {} improved system prompt variants as a JSON array of strings.",
            current_prompt,
            self.config.good_threshold,
            good_section,
            self.config.bad_threshold,
            bad_section,
            self.config.variants_to_generate
        );

        let messages = vec![
            ChatMessage {
                role: "system".to_string(),
                content: GENERATE_VARIANTS_PROMPT.to_string(),
                tool_calls: None,
                tool_call_id: None,
            },
            ChatMessage {
                role: "user".to_string(),
                content: user_message,
                tool_calls: None,
                tool_call_id: None,
            },
        ];

        let response = router.chat_with_tools(&messages, &[], "auto").await?;
        let text = response.message.content.trim().to_string();

        // Parse JSON array of strings from the response
        parse_variant_array(&text)
    }

    /// Evaluate a single prompt variant against test examples using LLM-as-Judge.
    ///
    /// Returns a score from 1.0 to 5.0 representing the predicted quality
    /// of outputs that would be produced using this variant prompt.
    async fn evaluate_variant(
        &self,
        variant_prompt: &str,
        test_examples: &[(String, String)],
        router: &LlmRouter,
    ) -> Result<f64> {
        if test_examples.is_empty() {
            return Err(anyhow!("No test examples provided for evaluation"));
        }

        // Format test examples
        let examples_section = test_examples
            .iter()
            .enumerate()
            .map(|(i, (input, expected_output))| {
                format!(
                    "### Test Example {}\nInput: {}\nReference good output: {}",
                    i + 1,
                    truncate(input, 500),
                    truncate(expected_output, 1000)
                )
            })
            .collect::<Vec<_>>()
            .join("\n\n");

        let user_message = format!(
            "## System Prompt to Evaluate\n{}\n\n\
             ## Test Examples\n{}\n\n\
             Score each test example (1-5) predicting how well this system prompt \
             would guide an LLM to produce output of similar quality to the reference.",
            variant_prompt, examples_section
        );

        let messages = vec![
            ChatMessage {
                role: "system".to_string(),
                content: EVALUATE_VARIANT_PROMPT.to_string(),
                tool_calls: None,
                tool_call_id: None,
            },
            ChatMessage {
                role: "user".to_string(),
                content: user_message,
                tool_calls: None,
                tool_call_id: None,
            },
        ];

        let response = router.chat_with_tools(&messages, &[], "auto").await?;
        let text = response.message.content.trim().to_string();

        // Parse the evaluation response
        parse_evaluation_response(&text)
    }

    /// Estimate the current prompt's score from trajectory quality data.
    ///
    /// Computes the mean quality_score of all trajectories that have a score,
    /// normalized to a 1.0-5.0 scale (treating the u8 score as 1-5).
    pub fn estimate_current_score(trajectories: &[TrajectoryEntry]) -> f64 {
        let scored: Vec<f64> = trajectories
            .iter()
            .filter_map(|t| t.quality_score.map(|s| s as f64))
            .collect();

        if scored.is_empty() {
            return 0.0;
        }

        scored.iter().sum::<f64>() / scored.len() as f64
    }
}

// ── Helper Functions ─────────────────────────────────────────────────────────

/// Parse a JSON array of strings from LLM output.
/// Handles markdown code blocks and extra text around the JSON.
fn parse_variant_array(text: &str) -> Result<Vec<String>> {
    let json_str = extract_json_block(text);

    let parsed: serde_json::Value = serde_json::from_str(&json_str)
        .map_err(|e| anyhow!("Failed to parse variant array JSON: {} — raw: {}", e, truncate(text, 200)))?;

    match parsed {
        serde_json::Value::Array(arr) => {
            let variants: Vec<String> = arr
                .into_iter()
                .filter_map(|v| v.as_str().map(String::from))
                .filter(|s| !s.trim().is_empty())
                .collect();

            if variants.is_empty() {
                Err(anyhow!("Parsed JSON array contained no valid string elements"))
            } else {
                Ok(variants)
            }
        }
        _ => Err(anyhow!("Expected JSON array, got: {}", parsed)),
    }
}

/// Parse the evaluation response and compute mean score.
/// Expected format: {"scores": [4, 3, 5], "reasoning": "..."}
fn parse_evaluation_response(text: &str) -> Result<f64> {
    let json_str = extract_json_block(text);

    let parsed: serde_json::Value = serde_json::from_str(&json_str)
        .map_err(|e| anyhow!("Failed to parse evaluation JSON: {} — raw: {}", e, truncate(text, 200)))?;

    let scores = parsed
        .get("scores")
        .and_then(|v| v.as_array())
        .ok_or_else(|| anyhow!("Missing 'scores' array in evaluation response"))?;

    if scores.is_empty() {
        return Err(anyhow!("Empty 'scores' array in evaluation response"));
    }

    let numeric_scores: Vec<f64> = scores
        .iter()
        .filter_map(|v| v.as_f64().or_else(|| v.as_u64().map(|u| u as f64)))
        .map(|s| s.clamp(1.0, 5.0))
        .collect();

    if numeric_scores.is_empty() {
        return Err(anyhow!("No valid numeric scores in evaluation response"));
    }

    Ok(numeric_scores.iter().sum::<f64>() / numeric_scores.len() as f64)
}

/// Extract a JSON block from LLM output.
/// Handles ```json ... ```, ``` ... ```, and raw JSON.
fn extract_json_block(text: &str) -> String {
    // Try to find ```json ... ```
    if let Some(start) = text.find("```json") {
        if let Some(end) = text[start + 7..].find("```") {
            return text[start + 7..start + 7 + end].trim().to_string();
        }
    }
    // Try to find ``` ... ``` with JSON content
    if let Some(start) = text.find("```") {
        if let Some(end) = text[start + 3..].find("```") {
            let inner = text[start + 3..start + 3 + end].trim();
            if inner.starts_with('{') || inner.starts_with('[') {
                return inner.to_string();
            }
        }
    }
    // Try to find raw JSON object first (more common in evaluation responses)
    if let Some(start) = text.find('{') {
        if let Some(end) = text.rfind('}') {
            if end > start {
                return text[start..=end].to_string();
            }
        }
    }
    // Try to find raw JSON array
    if let Some(start) = text.find('[') {
        if let Some(end) = text.rfind(']') {
            if end > start {
                return text[start..=end].to_string();
            }
        }
    }
    text.to_string()
}

/// Truncate a string to a maximum number of characters (respects char boundaries).
fn truncate(s: &str, max_chars: usize) -> &str {
    match s.char_indices().nth(max_chars) {
        Some((i, _)) => &s[..i],
        None => s,
    }
}

// ── Utility: Split Trajectories ──────────────────────────────────────────────

/// Split trajectories into good and bad buckets based on quality thresholds.
/// Returns (good_examples, bad_examples) as (input, output) pairs.
pub fn split_trajectories(
    trajectories: &[TrajectoryEntry],
    good_threshold: u8,
    bad_threshold: u8,
) -> (Vec<(String, String)>, Vec<(String, String)>) {
    let good: Vec<(String, String)> = trajectories
        .iter()
        .filter(|t| t.quality_score.map(|s| s >= good_threshold).unwrap_or(false))
        .map(|t| (t.prompt.clone(), t.output.clone()))
        .collect();

    let bad: Vec<(String, String)> = trajectories
        .iter()
        .filter(|t| t.quality_score.map(|s| s <= bad_threshold).unwrap_or(false))
        .map(|t| (t.prompt.clone(), t.output.clone()))
        .collect();

    (good, bad)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Create a test TrajectoryEntry with the required fields populated.
    /// Fields not relevant to the optimizer are filled with sensible defaults.
    fn make_trajectory(
        prompt: &str,
        output: &str,
        quality_score: Option<u8>,
        success: bool,
    ) -> TrajectoryEntry {
        TrajectoryEntry {
            id: uuid_stub(),
            session_id: None,
            agent_name: "test_agent".to_string(),
            hand_name: Some("test_hand".to_string()),
            phase_name: Some("test_phase".to_string()),
            provider: "ollama".to_string(),
            model: "llama3.2".to_string(),
            prompt: prompt.to_string(),
            output: output.to_string(),
            tool_calls: 0,
            tool_names: Vec::new(),
            total_tokens: 100,
            duration_secs: 1.0,
            estimated_cost_usd: 0.001,
            quality_score,
            guardrail_issues: Vec::new(),
            success,
            error_message: None,
            worker_name: None,
            worker_latency_ms: None,
            created_at: "2026-03-15T12:00:00Z".to_string(),
            date_key: "2026-03-15".to_string(),
        }
    }

    /// Generate a simple unique-ish ID for tests (not a real UUID).
    fn uuid_stub() -> String {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        format!("test-{}", COUNTER.fetch_add(1, Ordering::Relaxed))
    }

    #[test]
    fn test_optimization_config_defaults() {
        let config = OptimizationConfig::default();
        assert_eq!(config.min_trajectories, 10);
        assert_eq!(config.variants_to_generate, 3);
        assert_eq!(config.good_threshold, 4);
        assert_eq!(config.bad_threshold, 2);
    }

    #[test]
    fn test_insufficient_data() {
        let rt = tokio::runtime::Runtime::new().unwrap();
        rt.block_on(async {
            let optimizer = PromptOptimizer::default();
            // Only 3 trajectories, need 10
            let trajectories: Vec<TrajectoryEntry> = (0..3)
                .map(|i| make_trajectory(&format!("prompt {}", i), "output", Some(3), true))
                .collect();

            // We cannot call optimize_phase without a real LlmRouter, but we can
            // verify the insufficient data check directly by simulating.
            assert!(trajectories.len() < optimizer.config.min_trajectories);

            // Verify the result type we'd get
            let result = OptimizationResult::InsufficientData {
                available: trajectories.len(),
                needed: optimizer.config.min_trajectories,
            };
            match result {
                OptimizationResult::InsufficientData { available, needed } => {
                    assert_eq!(available, 3);
                    assert_eq!(needed, 10);
                }
                _ => panic!("Expected InsufficientData"),
            }
        });
    }

    #[test]
    fn test_estimate_current_score() {
        // Mix of scored and unscored trajectories
        let trajectories = vec![
            make_trajectory("p1", "o1", Some(5), true),
            make_trajectory("p2", "o2", Some(3), true),
            make_trajectory("p3", "o3", None, true),    // no score — should be ignored
            make_trajectory("p4", "o4", Some(4), true),
            make_trajectory("p5", "o5", Some(2), false),
        ];

        let score = PromptOptimizer::estimate_current_score(&trajectories);
        // (5 + 3 + 4 + 2) / 4 = 3.5
        assert!((score - 3.5).abs() < f64::EPSILON);
    }

    #[test]
    fn test_estimate_current_score_no_scores() {
        let trajectories = vec![
            make_trajectory("p1", "o1", None, true),
            make_trajectory("p2", "o2", None, true),
        ];
        let score = PromptOptimizer::estimate_current_score(&trajectories);
        assert!((score - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_estimate_current_score_empty() {
        let score = PromptOptimizer::estimate_current_score(&[]);
        assert!((score - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_split_trajectories() {
        let trajectories = vec![
            make_trajectory("good1", "excellent output", Some(5), true),
            make_trajectory("good2", "great output", Some(4), true),
            make_trajectory("mid1", "ok output", Some(3), true),
            make_trajectory("bad1", "poor output", Some(2), false),
            make_trajectory("bad2", "terrible output", Some(1), false),
            make_trajectory("unscored", "no score", None, true),
        ];

        let (good, bad) = split_trajectories(&trajectories, 4, 2);

        // Good: score >= 4 → "good1" (5) and "good2" (4)
        assert_eq!(good.len(), 2);
        assert_eq!(good[0].0, "good1");
        assert_eq!(good[1].0, "good2");

        // Bad: score <= 2 → "bad1" (2) and "bad2" (1)
        assert_eq!(bad.len(), 2);
        assert_eq!(bad[0].0, "bad1");
        assert_eq!(bad[1].0, "bad2");
    }

    #[test]
    fn test_split_trajectories_empty() {
        let (good, bad) = split_trajectories(&[], 4, 2);
        assert!(good.is_empty());
        assert!(bad.is_empty());
    }

    #[test]
    fn test_split_trajectories_no_extremes() {
        // All scores are 3 — neither good (>=4) nor bad (<=2)
        let trajectories = vec![
            make_trajectory("m1", "medium1", Some(3), true),
            make_trajectory("m2", "medium2", Some(3), true),
        ];
        let (good, bad) = split_trajectories(&trajectories, 4, 2);
        assert!(good.is_empty());
        assert!(bad.is_empty());
    }

    #[test]
    fn test_parse_variant_array_clean() {
        let input = r#"["prompt variant 1", "prompt variant 2", "prompt variant 3"]"#;
        let variants = parse_variant_array(input).unwrap();
        assert_eq!(variants.len(), 3);
        assert_eq!(variants[0], "prompt variant 1");
    }

    #[test]
    fn test_parse_variant_array_markdown() {
        let input = "Here are the variants:\n```json\n[\"variant 1\", \"variant 2\"]\n```\nDone.";
        let variants = parse_variant_array(input).unwrap();
        assert_eq!(variants.len(), 2);
    }

    #[test]
    fn test_parse_variant_array_with_surrounding_text() {
        let input = "Sure! [\"improved prompt A\", \"improved prompt B\"] Hope this helps!";
        let variants = parse_variant_array(input).unwrap();
        assert_eq!(variants.len(), 2);
    }

    #[test]
    fn test_parse_variant_array_filters_empty() {
        let input = r#"["good prompt", "", "  ", "another good one"]"#;
        let variants = parse_variant_array(input).unwrap();
        assert_eq!(variants.len(), 2);
        assert_eq!(variants[0], "good prompt");
        assert_eq!(variants[1], "another good one");
    }

    #[test]
    fn test_parse_variant_array_not_array() {
        let input = r#"{"key": "value"}"#;
        assert!(parse_variant_array(input).is_err());
    }

    #[test]
    fn test_parse_evaluation_response() {
        let input = r#"{"scores": [4, 5, 3], "reasoning": "Generally good"}"#;
        let score = parse_evaluation_response(input).unwrap();
        // (4 + 5 + 3) / 3 = 4.0
        assert!((score - 4.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_parse_evaluation_response_clamps() {
        let input = r#"{"scores": [10, 0, 3], "reasoning": "Extreme scores"}"#;
        let score = parse_evaluation_response(input).unwrap();
        // Clamped: (5 + 1 + 3) / 3 = 3.0
        assert!((score - 3.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_parse_evaluation_response_missing_scores() {
        let input = r#"{"reasoning": "No scores"}"#;
        assert!(parse_evaluation_response(input).is_err());
    }

    #[test]
    fn test_parse_evaluation_response_empty_scores() {
        let input = r#"{"scores": [], "reasoning": "Empty"}"#;
        assert!(parse_evaluation_response(input).is_err());
    }

    #[test]
    fn test_extract_json_block_raw_object() {
        let input = r#"Here: {"key": "value"} done."#;
        let json = extract_json_block(input);
        assert_eq!(json, r#"{"key": "value"}"#);
    }

    #[test]
    fn test_extract_json_block_raw_array() {
        let input = r#"Result: ["a", "b"] end."#;
        let json = extract_json_block(input);
        assert_eq!(json, r#"["a", "b"]"#);
    }

    #[test]
    fn test_extract_json_block_markdown_json() {
        let input = "Output:\n```json\n{\"x\": 1}\n```";
        let json = extract_json_block(input);
        assert_eq!(json, r#"{"x": 1}"#);
    }

    #[test]
    fn test_extract_json_block_markdown_generic() {
        let input = "Output:\n```\n[\"a\"]\n```";
        let json = extract_json_block(input);
        assert_eq!(json, r#"["a"]"#);
    }

    #[test]
    fn test_truncate_short() {
        assert_eq!(truncate("hello", 10), "hello");
    }

    #[test]
    fn test_truncate_exact() {
        assert_eq!(truncate("hello", 5), "hello");
    }

    #[test]
    fn test_truncate_long() {
        assert_eq!(truncate("hello world", 5), "hello");
    }

    #[test]
    fn test_truncate_unicode() {
        // 繁體中文 — 4 characters, each multi-byte
        let s = "繁體中文測試";
        let t = truncate(s, 4);
        assert_eq!(t, "繁體中文");
    }

    #[test]
    fn test_prompt_optimizer_new() {
        let config = OptimizationConfig {
            min_trajectories: 5,
            variants_to_generate: 2,
            good_threshold: 3,
            bad_threshold: 1,
        };
        let optimizer = PromptOptimizer::new(config);
        assert_eq!(optimizer.config.min_trajectories, 5);
        assert_eq!(optimizer.config.variants_to_generate, 2);
        assert_eq!(optimizer.config.good_threshold, 3);
        assert_eq!(optimizer.config.bad_threshold, 1);
    }

    #[test]
    fn test_optimization_result_variants() {
        // Verify all enum variants can be constructed
        let improved = OptimizationResult::Improved {
            new_prompt: "better prompt".to_string(),
            score_delta: 0.5,
            reasoning: "It's better".to_string(),
        };
        assert!(matches!(improved, OptimizationResult::Improved { .. }));

        let no_improvement = OptimizationResult::NoImprovement { current_score: 3.5 };
        assert!(matches!(no_improvement, OptimizationResult::NoImprovement { .. }));

        let insufficient = OptimizationResult::InsufficientData {
            available: 3,
            needed: 10,
        };
        assert!(matches!(insufficient, OptimizationResult::InsufficientData { .. }));

        let error = OptimizationResult::Error("something went wrong".to_string());
        assert!(matches!(error, OptimizationResult::Error(_)));
    }

    #[test]
    fn test_prompt_candidate_struct() {
        let candidate = PromptCandidate {
            prompt: "You are a helpful assistant.".to_string(),
            score: 4.2,
            reasoning: "Clear and specific instructions".to_string(),
        };
        assert_eq!(candidate.score, 4.2);
        assert!(candidate.prompt.contains("helpful"));
    }

    #[test]
    fn test_config_serde_roundtrip() {
        let config = OptimizationConfig {
            min_trajectories: 20,
            variants_to_generate: 5,
            good_threshold: 5,
            bad_threshold: 1,
        };
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: OptimizationConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.min_trajectories, 20);
        assert_eq!(deserialized.variants_to_generate, 5);
        assert_eq!(deserialized.good_threshold, 5);
        assert_eq!(deserialized.bad_threshold, 1);
    }
}
